languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon EKS Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = "UA-44634850-4"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/aws-samples/eks-workshop/edit/master/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon EKS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "https://github.com/aws-samples/eks-workshop/"
branch = "master"
template_bucket = "eksworkshop.com"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"



#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-aws'></i> CON203"
url = "/tags/CON203"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-aws'></i> CON205"
url = "/tags/CON205"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-aws'></i> CON206"
url = "/tags/CON206"
weight = 3

[[menu.shortcuts]]
name = "<i class='fab fa-aws'></i> OPN401"
url = "/tags/OPN401"
weight = 4

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 5

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AppMesh Workshop"
url = "https://appmeshworkshop.com"
weight = 6

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> ECS Workshop"
url = "https://ecsworkshop.com"
weight = 7

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> More Resources"
url = "/more_resources"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/aws-samples/eks-workshop"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "mailto:eksworkshop@amazon.com"
weight = 40


[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
