languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amazon EKS Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = "UA-44634850-4"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon EKS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github Project"
url = "https://github.com/aws-samples/eks-workshop"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> More Resources"
url = "/more_resources"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Authors"
url = "/authors"
weight = 30

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
